apiVersion: v1
kind: Secret
metadata:
  name: my-postgresql-credentials
type: Opaque
data:
  password: ZmFzdGFwaQo=
  username: ZmFzdGFwaQo=

# PGPASSWORD='fastapi' psql -h 127.0.0.1 -U fastapi -d fastapi -c "

# CREATE TABLE fastapi();"